# Generated by Django 5.2.17 on 2026-09-23 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('industry', models.CharField(max_length=80, verbose_name='Тема')),
                ('draft', models.TextField(verbose_name='Первоначальное описание')),
                ('context', models.TextField(blank=True, verbose_name='Контекст')),
                ('need', models.TextField(blank=True, verbose_name='Потребность')),
                ('users', models.TextField(blank=True, verbose_name='Пользователи')),
                ('data', models.TextField(blank=True, verbose_name='Данные и материалы')),
                ('constraints', models.TextField(blank=True, verbose_name='Ограничения')),
                ('result', models.TextField(blank=True, verbose_name='Ожидаемый результат')),
                ('success', models.TextField(blank=True, verbose_name='Критерии успеха')),
                ('contact', models.CharField(blank=True, max_length=250, verbose_name='Контакт')),
                ('interaction', models.TextField(blank=True, verbose_name='Формат взаимодействия')),
                ('confirmed', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Команда')),
                ('interests', models.CharField(max_length=250, verbose_name='Интересы')),
                ('skills', models.CharField(max_length=250, verbose_name='Навыки и технологии')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField(verbose_name='Идея решения')),
                ('plan', models.TextField(verbose_name='План работы')),
                ('duration', models.CharField(max_length=120, verbose_name='Срок')),
                ('prototype', models.URLField(blank=True, verbose_name='Ссылка на прототип')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('selected', 'Выбрана'), ('rejected', 'Отклонена')], default='pending', max_length=12)),
                ('evidence', models.TextField(blank=True, verbose_name='Результат этапа / ссылка на работу')),
                ('progress_confirmed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.team')),
            ],
        ),
    ]
