# Generated by Django 5.2.17 on 2026-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quality_reviews',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
